name: Build Project

env:
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v3


    - name: Build Web
      working-directory: ./src/Piligrimm.Server/Web
      run: dotnet build --no-restore