name: Build Project

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:

      - name: Build Web
        working-directory: src/Piligrimm.Server/Web
        run: dotnet build

      # Test